'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SKUD.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Excel_panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel_panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;ru&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;Выгрузка отпусков и графиков работы&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }
        '''        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        '''        h2 { color: #34495e; margin-top: 30px; }
        '''        h3 { color: #7f8c8d; }
        '''        .step { background-color: #f8f9fa; p [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property export_instruction() As String
            Get
                Return ResourceManager.GetString("export_instruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Export_parametri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Export_parametri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;ru&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;Выгрузка отчета из СКУД&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }
        '''        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        '''        h2 { color: #34495e; margin-top: 30px; }
        '''        .step { background-color: #f8f9fa; padding: 15px; margin: 10px 0; border-left: 4 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property export_report_instruction() As String
            Get
                Return ResourceManager.GetString("export_report_instruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Export_v_Excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Export_v_Excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Generator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Generator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grafik_raboti_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grafik_raboti_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grafik_raboti_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grafik_raboti_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nastroiki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nastroiki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Otpusk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Otpusk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sotrudniki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sotrudniki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property URV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("URV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html lang=&quot;ru&quot;&gt;
        '''&lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        '''    &lt;title&gt;Инструкция по использованию СКУД&lt;/title&gt;
        '''    &lt;style&gt;
        '''        body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }
        '''        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        '''        h2 { color: #34495e; margin-top: 30px; }
        '''        h3 { color: #7f8c8d; }
        '''        .step { background-color: #f8f9fa; padding: 15px;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property user_instruction() As String
            Get
                Return ResourceManager.GetString("user_instruction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ustanovit_soed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ustanovit_soed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
